# Generated by Django 2.2.7 on 2019-11-29 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='daily_rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 13, 46, 33, 478734, tzinfo=utc)),
        ),
    ]
